/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_agemark_AgeRenderer */

#ifndef _Included_com_tencent_agemark_AgeRenderer
#define _Included_com_tencent_agemark_AgeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_agemark_AgeRenderer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_agemark_AgeRenderer
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_tencent_agemark_AgeRenderer
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeRender
  (JNIEnv *, jclass);

/*
 * Class:     com_tencent_agemark_AgeRenderer
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeDone
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
