/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <GLES/gl.h>
#include "AgeMark.h"


extern "C"
{
	/*
	 * Class:     com_tencent_agemark_AgeRenderer
	 * Method:    nativeInit
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeInit
	(JNIEnv * env, jclass cls)
	{
		initializeOpenGL();
	}

	/*
	 * Class:     com_tencent_agemark_AgeRenderer
	 * Method:    nativeResize
	 * Signature: (II)V
	 */
	JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeResize
	(JNIEnv * evn, jclass clas, jint width, jint height)
	{
		resizeViewport(width, height);
	}

	/*
	 * Class:     com_tencent_agemark_AgeRenderer
	 * Method:    nativeRender
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeRender
	(JNIEnv * env, jclass cls)
	{
		renderFrame();
	}

	/*
	 * Class:     com_tencent_agemark_AgeRenderer
	 * Method:    nativeDone
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_tencent_agemark_AgeRenderer_nativeDone
	(JNIEnv *env, jclass cls)
	{

	}
}
